// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbzM0nZ5B8eeK9QdCbjp4O7dHrXI1R4o',
    appId: '1:795912776219:web:79fde064cd53078d7666be',
    messagingSenderId: '795912776219',
    projectId: 'finmo-bd301',
    authDomain: 'finmo-bd301.firebaseapp.com',
    storageBucket: 'finmo-bd301.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLQOUG_WTdnAryBKYVF4zy_lDbFKtj5Q',
    appId: '1:795912776219:android:1897badea6c28cbf7666be',
    messagingSenderId: '795912776219',
    projectId: 'finmo-bd301',
    storageBucket: 'finmo-bd301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6inOS-tQi3blzssR4cHLmh34xxRpsrgE',
    appId: '1:795912776219:ios:f478bda9249cc7907666be',
    messagingSenderId: '795912776219',
    projectId: 'finmo-bd301',
    storageBucket: 'finmo-bd301.firebasestorage.app',
    iosBundleId: 'com.example.finmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6inOS-tQi3blzssR4cHLmh34xxRpsrgE',
    appId: '1:795912776219:ios:f478bda9249cc7907666be',
    messagingSenderId: '795912776219',
    projectId: 'finmo-bd301',
    storageBucket: 'finmo-bd301.firebasestorage.app',
    iosBundleId: 'com.example.finmo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbzM0nZ5B8eeK9QdCbjp4O7dHrXI1R4o',
    appId: '1:795912776219:web:1ca20118ddd60f2e7666be',
    messagingSenderId: '795912776219',
    projectId: 'finmo-bd301',
    authDomain: 'finmo-bd301.firebaseapp.com',
    storageBucket: 'finmo-bd301.firebasestorage.app',
  );
}
